// This code was automatically generated by the ApiGenerator plugin.
// Prefer updating the generator code instead of editing this directly.
// "u[]" variables are unknown data.

// Example entity: func_tank
class CBaseTank {
public:
    byte u0[4];
    entvars_t* pev; // Entity variables
    byte u1[48];
    bool m_fOverrideClass; // Whether this entity overrides the classification.
    byte u2[3];
    int m_iClassSelection; // The overridden classification.
    byte u3[20];
    float m_flMaximumFadeWait; // Maximum fade wait time.
    float m_flMaximumFadeWaitB; // Maximum fade wait time B.
    bool m_fCanFadeStart; // Whether fading can start.
    byte u4[11];
    bool m_fCustomModel; // Whether a custom model is used.
    byte u5[3];
    vec3_t m_vecLastOrigin; // Last origin vector
    string_t targetnameOutFilterType; // Target name out filter type.
    string_t classnameOutFilterType; // Class name out filter type.
    string_t targetnameInFilterType; // Target name in filter type.
    string_t classnameInFilterType; // Class name in filter type.
    byte u6[16];
    int m_iOriginalRenderMode; // Original render model.
    int m_iOriginalRenderFX; // Original render FX.
    float m_flOriginalRenderAmount; // Original render amount.
    vec3_t m_vecOriginalRenderColor; // Original render color.
    byte u7[184];
    float m_yawCenter; // "Center" yaw
    float m_yawRate; // Max turn rate to track targets
    float m_yawRange; // Range of turning motion (one-sided: 30 is +/- 30 degress from center)<br>Zero is full rotation
    float m_pitchCenter; // "Center" pitch
    byte u8[8];
    float m_flNextAttack; // Next attack time
    vec3_t m_vecControllerUsePos; // Start origin of the player that is currently controlling this tank.<br>Used to determine when a player has moved too far to continue controlling this tank.
    float m_yawTolerance; // Tolerance angle
    float m_pitchRate; // Max turn rate on pitch
    float m_pitchRange; // Range of pitch motion as above
    float m_pitchTolerance; // Tolerance angle
    float m_fireLast; // Last time I fired
    float m_fireRate; // How many rounds/second
    float m_lastSightTime; // Last time I saw target
    float m_persist; // Persistence of firing (how long do I shoot when I can't see)
    float m_minRange; // Minimum range to aim/track
    float m_maxRange; // Max range to aim/track
    vec3_t m_barrelPos; // Length of the freakin barrel
    float m_spriteScale; // Scale of any sprites we shoot
    byte u9[8];
    int m_bulletType; // Bullet type
    int m_iBulletDamage; // 0 means use Bullet type's default damage
    vec3_t m_sightOrigin; // Last sight of target
    int m_spread; // firing spread
    string_t m_iszMaster; // Master entity (game_team_master or multisource)
};
