// This code was automatically generated by the ApiGenerator plugin.

// declaring classes that might be used as function arguments or return types before they're defined
class CBaseEntity;
class CBaseDelay;
class CBaseAnimating;
class CBaseToggle;
class CBaseButton;
class CBaseMonster;
class CBasePlayer;
class CCineMonster;
class CBasePlayerItem;
class CBasePlayerWeapon;
class CBaseTank;
class CItemInventory;
class CPathTrack;

#include "sc_enums.h"
#include "EHandle.h"
#include "CBaseEntity.h"
#include "CBaseDelay.h"
#include "CBaseAnimating.h"
#include "CBaseToggle.h"
#include "CBaseButton.h"
#include "CBaseMonster.h"
#include "CBasePlayer.h"
#include "CCineMonster.h"
#include "CBasePlayerItem.h"
#include "CBasePlayerWeapon.h"
#include "CBaseTank.h"
#include "CItemInventory.h"
#include "CPathTrack.h"
